// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0cxVzl0DTEyk71XNgGw39V5-XsF0CV3I',
    appId: '1:218586654200:web:8c4b2f76a2f88b4a96a20d',
    messagingSenderId: '218586654200',
    projectId: 'civicmonitor-f3b39',
    authDomain: 'civicmonitor-f3b39.firebaseapp.com',
    storageBucket: 'civicmonitor-f3b39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACwh3FuKk5Chu4pqS1Gp4q-O6w8iPybP0',
    appId: '1:218586654200:android:b1681934a6fd620196a20d',
    messagingSenderId: '218586654200',
    projectId: 'civicmonitor-f3b39',
    storageBucket: 'civicmonitor-f3b39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxspF_cSghjBfwbTDHwSsNpEqici-uCHc',
    appId: '1:218586654200:ios:71f656f9725e594596a20d',
    messagingSenderId: '218586654200',
    projectId: 'civicmonitor-f3b39',
    storageBucket: 'civicmonitor-f3b39.appspot.com',
    iosBundleId: 'com.example.civicmonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxspF_cSghjBfwbTDHwSsNpEqici-uCHc',
    appId: '1:218586654200:ios:71f656f9725e594596a20d',
    messagingSenderId: '218586654200',
    projectId: 'civicmonitor-f3b39',
    storageBucket: 'civicmonitor-f3b39.appspot.com',
    iosBundleId: 'com.example.civicmonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0cxVzl0DTEyk71XNgGw39V5-XsF0CV3I',
    appId: '1:218586654200:web:80ac5ba88bcf0bd696a20d',
    messagingSenderId: '218586654200',
    projectId: 'civicmonitor-f3b39',
    authDomain: 'civicmonitor-f3b39.firebaseapp.com',
    storageBucket: 'civicmonitor-f3b39.appspot.com',
  );
}
